### ISSUE TITLE
Use git checker to fetch GitHub release artifacts

### ISSUE THREAD

**Issue by ghisvail** [flathub-infra/flatpak-external-data-checker#164]
I have a few apps which are repacking of a DEB package available through GitHub releases and where no other means to fetch the latest version is available.

Can I use the git-checker to monitor the latest git tag, compile the corresponding URL of the DEB package and submit a PR automatically, like it does for the HTTP checker?

**Comment by gasinvein** [comment]
No, git checker works only with git repos. But you can use json checker to query github API. Here is an example of retrieving a GH release asset by its name:
```yaml
        x-checker-data:
          type: json
          url: https://api.github.com/repos/fish-shell/fish-shell/releases/latest
          version-query: .tag_name | sub("^[vV]"; "")
          url-query: .assets[] | select(.name=="fish-\($version).tar.xz") | .browser_download_url
```
(if you're unfamiliar with `jq`, see its [manual](https://stedolan.github.io/jq/manual/), or just ask here if unsure how to to adapt the example above for your app)
