### ISSUE TITLE
Anitya checker: support "version"

### ISSUE THREAD

**Issue by vrutkovs** [flathub-infra/flatpak-external-data-checker#174]
"versions" param (similar to GNOME checker) would enable us to track minor versions (i.e.
```
        x-checker-data:
          type: anitya
          project-id: 1227
          versions:
            <: 1.16.0
          url-template: https://golang.org/dl/go$version.linux-amd64.tar.gz
``` 
to track go 1.15 versions
