### ISSUE TITLE
How to avoid beta versions from pypi

### ISSUE THREAD

**Issue by sophie-h** [flathub-infra/flatpak-external-data-checker#176]
I have the following check

```yaml
        x-checker-data:
          type: pypi
          name: borgbackup
          versions: { "<": "1.2" }
```

and the report says

```yaml
CHANGE SOON: borgbackup-1.1.16.tar.gz
 Has a new version:
  URL:       https://files.pythonhosted.org/packages/83/4a/95725c920aecb0fc00fb58604fe3c8e5c79a1f92a3b857a9c6ffacd312e6/borgbackup-1.2.0b2.tar.gz
  SHA256:    82b6100cb9db7113dd8c082ac9c9e1de7bd538eb9cb685c2cf499a34e1bac64d
  Size:      3940922
  Version:   1.2.0b2
  Timestamp: 2021-02-06 13:18:31.784134
```

I can work around this by using `"<": "1.1.99"` but maybe I will get a `1.1.x` beta version with this? Any way to fix this?

PS: Also I could not find docs that say that `versions` is even supported for pypi.
