### ISSUE TITLE
Git checker confused when tag isn't quoted

### ISSUE THREAD

**Issue by vchernin** [flathub-infra/flatpak-external-data-checker#206]
The Git checker behaves unexpectedly when the tag isn't surrounded by quotation marks, and offers updates to a fully up-to-data module.

I could only reproduce this issue with this module and github repo and not others that I tried, not sure why, I can try more if it helps. 

For reference, this [`zam-plugins`](https://github.com/zamaudio/zam-plugins/) module's latest tag is 3.14. Since that tag is already in the manifest, no newer version should be offered. This was found working on [this PR](https://github.com/flathub/flathub/pull/2429). 

Having the tag in `tag: 3.14` not surrounded by quotation marks:
```
          - name: zam-plugins
            no-autogen: true
            make-args:
              - "PREFIX=${FLATPAK_DEST}"
              - PLUGINS=ZaMaximX2
            make-install-args:
              - "PREFIX=${FLATPAK_DEST}"
              - PLUGINS=ZaMaximX2
            build-options:
              arch:
                aarch64:
                  make-args:
                    - NOOPT=true
                arm:
                  make-args:
                    - NOOPT=true
            sources:
             - type: git
                url: 'https://github.com/zamaudio/zam-plugins.git'
                tag: 3.14
                commit: e7077fcc0b7f60daa7471eae42015ffc9cba73d9
                x-checker-data:
                  type: git
                  tag-pattern: "^([\\d.]+)"
            post-install:
              - install -Dm644 -t $FLATPAK_DEST/share/licenses/zam-plugins COPYING
            cleanup:
              - /lib/lv2
              - /lib/vst
```
`flatpak run org.flathub.flatpak-external-data-checker` outputs:
```
CHANGE SOON: zam-plugins.git
 Has a new version:
  URL:       https://github.com/zamaudio/zam-plugins.git
  Commit:    e7077fcc0b7f60daa7471eae42015ffc9cba73d9
  Tag:       3.14
  Branch:    None
  Version:   3.14
  Timestamp: None
```
Which is unexpected given this update isn't changing anything.

To workaround this I changed `tag: 3.14` to `tag: "3.14"`

Outputs no "CHANGE SOON" entry which is expected.

To reproduce try cloning [this repo](https://github.com/vchernin/flathub/tree/com.github.wwmm.easyeffects) and running f-e-d-c and removing the quotations from `tag: "3.14".

Should f-e-d-c just error out if people don't use quotations here?

**Comment by gasinvein** [comment]
I believe in `tag: 3.14` the `3.14` is interpreted as a number, so it should be quoted indeed to be a string.

**Comment by vchernin** [comment]
Yes, however what is strange is that only some tags need to be quoted while others seemingly don't.

For example if I try with gtkmm
```
    - name: gtkmm
        buildsystem: meson
        config-opts:
        - -Dbuild-documentation=false
        sources:
        - type: git
          url: 'https://gitlab.gnome.org/GNOME/gtkmm.git'
          tag: 4.2.0
          commit: e0e280baf48b9899b1870a3308ea8fb31c83ebb5
          x-checker-data:
            type: git
            tag-pattern: "^([\\d.]+)"

          cleanup:
          - '/lib/gdkmm*'
          - '/lib/gtkmm*'
        modules:
```
I am not able to reproduce the issue. Not including quotations works properly. 

Possible reasons:
- 3.14 is assumed to be a number, while 4.2.0 is assumed to be a string due to the 2 decimals?
- Differences between how authors tagged their work?
- Maybe it's due to github behaving slightly differently from gitlab?
