### ISSUE TITLE
git checker needs commit

### ISSUE THREAD

**Issue by JakobDev** [flathub-infra/flatpak-external-data-checker#301]
I have the following sources in one of my manifests:
```yaml
sources:
  - type: git
    url: https://gitlab.com/JakobDev/jdTextEdit.git
    tag: '10.1'
    x-checker-data:
      type: git
      url: https://gitlab.com/JakobDev/jdTextEdit.git
      tag-pattern: "(.+)"
```
The tag porperty is valid and it will build everytime from this tag. But f-e-d-c says this:
```
State.LATEST|BROKEN: jdTextEdit.git
 Has a new version:
  URL:       https://gitlab.com/JakobDev/jdTextEdit.git
  Commit:    cb1f9d200e76cd5ccca714ea281c8b7827c7b9b2
  Tag:       10.1
  Branch:    None
  Version:   10.1
  Timestamp: None
```
It says that there is a newer tag, but it's the same tag. The solution was to add the commit to the sources, which is totally unnecessary since the tag is all what is needed to build. Would be nice, if f-e-d-c could work without the commit property.
