### ISSUE TITLE
Documentation: variable substitution in url templates

### ISSUE THREAD

**Issue by Gaeldrin** [flathub-infra/flatpak-external-data-checker#337]
When using version substitution in `url-template`, it counts underscore as part of the variable name (which is ok) without any obvious way to make the underscore part of URL instead (which is not ok as it is impossible to construct real world URL), e.g.:
```
url: https://get.geo.opera.com/pub/opera/desktop/94.0.4606.38/linux/Opera_94.0.4606.38_amd64.deb
x-checker-data:
  type: anitya
  project-id: 7242
  url-template: https://get.geo.opera.com/pub/opera/desktop/$version/linux/Opera_$version_amd64.deb
```
results in:

`ERROR   src.manifest: Failed to check file opera/opera.deb with AnityaChecker: Error substituting template: 'version_amd64'`

Edit: I could actually make it work by using folded brackets (e.g. `Opera_${version}_amd64.deb`) thanks to previous experience with shell but I still think that it could be improvement to mention this in the documentation (together with info if `version` is the only variable).
