### ISSUE TITLE
Version constraining to even/odd versions

### ISSUE THREAD

**Issue by darkdragon-001** [flathub-infra/flatpak-external-data-checker#344]
Some packages use even/odd versioning for stable/unstable version numbers (see [Wikipedia](https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases)). It would be nice if one could restrain versions in such a way that only stable numbers are proposed.

**Comment by wjt** [comment]
The GNOME checker supports GNOME's (previous) similar scheme. It does seem a reasonable addition elsewhere.

In the linked case of Calls you could fake it with:

```yaml
        x-checker-data:
          type: git
          #version-scheme: semantic
          tag-pattern: ^(\d+\.\d*[02468]\.\d+)$
```
