### ISSUE TITLE
Version constraining - Multiple !=

### ISSUE THREAD

**Issue by kevinlekiller** [flathub-infra/flatpak-external-data-checker#363]
Is there any way to ignore 2 release versions, but allow older / newer releases.

I'll use the example of https://github.com/flathub/io.mpv.Mpv below:

yt-dlp's versions 2023.03.04 (the latest version) and 2023.03.03 have issues, the previous version before that (2023.02.17) works fine.

This doesn't work :

`versions: {'!=': '2023.03.03', '!=': '2023.03.04'}` (since we can't have multiple not equals)

Being able to have multiple not equals or regex would be nice, like this:

`versions: {'!=': '2023.03.0[34]'}`

Or maybe there's another way?

**Comment by wjt** [comment]
I ran into this limitation the other day. Possible syntaxes if someone wanted to extend the `"versions"` feature to support this, none of which are exactly beautiful, and **none of which work today**:

```yaml
versions:
  '&&': [
    {'!=': '2023.03.03'},
    {'!=': '2023.03.04'},
  ]
```

```yaml
versions: {'!=': ['2023.03.03', '2023.03.04'}
```

```yaml
versions: {'∉': ['2023.03.03', '2023.03.04'}
```

```yaml
versions: {'not in': ['2023.03.03', '2023.03.04'}
```

You could do this as a gross but functional workaround:

```yaml
    sources:
      - type: archive
        url: https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/yt-dlp.tar.gz
        sha256: 81f607b8754b1bc67e6592a4e316c015d720e7118757a5afd4ef2aaf37d2ef29
        x-checker-data:
          type: json
          url: https://api.github.com/repos/yt-dlp/yt-dlp/releases
          version-query: map(select( .draft | not )) | map(select(.tag_name != "2023.03.03" and .tag_name != "2023.03.04")) | .[0].tag_name
          url-query: "https://github.com/yt-dlp/yt-dlp/releases/download/" + $version + "/yt-dlp.tar.gz"
```

YAML quoting left as an exercise to the reader, I only tested these at the `jq` command line.
