### ISSUE TITLE
Help needed: Failed to check archive cudatext/1.205.5.2.tar.gz with JSONChecker

### ISSUE THREAD

**Issue by faveoled** [flathub-infra/flatpak-external-data-checker#408]
Checker file:
```
      - type: archive
        url: https://github.com/Alexey-T/CudaText/archive/refs/tags/1.205.5.2.tar.gz
        sha256: 0a5ce1bad9fa86a8de138e093df87a883d8740663a70330d272a7caed3c21656
        dest: src/CudaText
        x-checker-data:
          type: "json"
          url: "https://api.github.com/repos/Alexey-T/CudaText/releases/latest"
          version-query: '.tag_name | sub(\"^jq-\"; \"\")'
          url-query: '.assets[] | select(.name==\"jq-\" + $version + \".tar.gz\") | .browser_download_url'
```
Error:
```
jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 1:
.tag_name | sub(\"^jq-\"; \"\")                
jq: 1 compile error
ERROR   src.manifest: Failed to check archive cudatext/1.205.5.2.tar.gz with JSONChecker: Error running jq: Command '['jq', '-e', '.tag_name | sub(\\"^jq-\\"; \\"\\")']' returned non-zero exit status 3.
```
Any ideas?

**Comment by wjt** [comment]
I don't think you need to escape the double quotes

**Comment by Alexander-Wilms** [comment]
Why not use the AnityaChecker? Seems a lot easier, even if introduces a few hours of delay:

https://release-monitoring.org/project/370760/

```
        x-checker-data:
          type: anitya
          project-id: 370760
          url-template: https://github.com/Alexey-T/CudaText/archive/refs/tags/$version.tar.gz
```
