### ISSUE TITLE
Flathubbot proposes downgrade for Minigalaxy

### ISSUE THREAD

**Issue by sharkwouter** [flathub-infra/flatpak-external-data-checker#430]
Here is the offending PR where a downgrade from 1.3.0 to 1.2.6 is proposed and presented as an upgrade: https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/56

This seems like a bug to me. Not sure what other info I could provide here. Let me know if I can.

**Comment by wjt** [comment]
It's just offering you the latest release on https://release-monitoring.org/project/292418, which is 1.2.6 – I guess it hasn't noticed the new release yet. The last poll there is shown as being on 2024-06-10, prior to the 1.3.0 release. For better or for worse, fedc doesn't compare the proposed update to what's already in the manifest.

You can avoid the indirection through anitya/release monitoring by monitoring the GitHub project directly. Something like this should work:

```yaml
        x-checker-data:
          type: json
          url: https://api.github.com/repos/sharkwouter/minigalaxy/releases/latest
          version-query: .tag_name
          url-query: '"https://github.com/sharkwouter/minigalaxy/archive/" + .tag_name + ".tar.gz"'
```
