### ISSUE TITLE
GNOME checker: bug if major version number is 0 and even/odd minor version scheme for stable/unstable releases

### ISSUE THREAD

**Issue by swilmet** [flathub-infra/flatpak-external-data-checker#436]
A follow-up of https://github.com/flathub/org.gnome.gedit/pull/126

For bundling VTE, gedit has this in the Flatpak manifest:
```
            x-checker-data:
              type: gnome
              name: vte
              stable-only: true
```

VTE has a major version of 0, and uses the even/odd minor version scheme.

The algorithm to determine if a gnome version is stable doesn't work in the case of VTE.

See https://github.com/flathub-infra/flatpak-external-data-checker/blob/master/src/checkers/gnomechecker.py

```python
def _is_stable(version: str) -> bool:
    # [...]
    if int(major) > 0 and int(major) < 40 and len(ver_list) > 2:
        return (int(minor) % 2) == 0
    # XXX If we didn't see any indication that the version is a prerelease,
    # assume it's a normal (stable) release
    return True
```

The last if condition in `_is_stable()` checks `int(major) > 0`. Perhaps that part just needs to be removed, or changed to `>= 0`.

**Comment by swilmet** [comment]
Maybe all VTE versions should be considered unstable, in which case it's better to rely on (for example):

```
x-checker-data:
  type: gnome
  name: vte
  versions:
    <: '0.81'
```

And update the condition every 6 months.

The `version-scheme` set to `odd-minor-is-unstable` still doesn't work in the case of VTE.

**Comment by bbhtt** [comment]
This should be fixed by https://github.com/flathub-infra/flatpak-external-data-checker/commit/5f240e1aa6c1fef012f704b6c8aa410290d3984f and https://github.com/flathub-infra/flatpak-external-data-checker/commit/1952a1b2650867f6e6eae64fea58085f4f1b0f6d I think.

I can see a correct upgrade from `0.76.3 -> 0.80.3` with this

```yaml
x-checker-data:
  type: gnome
  name: vte
  stable-only: true
  version-scheme: odd-minor-is-unstable
```

Feel free to reopen if not.
