### ISSUE TITLE
Unable to ignore protobuf versions 30+

### ISSUE THREAD

**Issue by ilya-fedin** [flathub-infra/flatpak-external-data-checker#465]
I have the following block but the bot continues to create PRs updating protobuf to 30.2
```
  - name: protobuf
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=None
      - -DBUILD_SHARED_LIBS=ON
      - -Dprotobuf_BUILD_TESTS=OFF
    sources:
      - type: git
        url: https://github.com/protocolbuffers/protobuf.git
        commit: 9fff46d7327c699ef970769d5c9fd0e44df08fc7
        tag: v28.2
        x-checker-data:
          type: json
          url: https://api.github.com/repos/protocolbuffers/protobuf/releases/latest
          tag-query: .tag_name
          timestamp-query: .published_at
          version-query: $tag | sub("^[vV]"; "")
          versions:
            <: '30'
    cleanup:
      - /bin
```
I also tried `<: '30.0'` but that doesn't work either
